packages:
  - packages/*
  - apps/*
  - '!**/test/**'

catalog:
  pg: ^8.16.3
  reflect-metadata: ^0.2.2
  typeorm: ^0.3.26
  '@eslint/eslintrc': ^3.3
  '@types/node': ^20
  eslint: ^9
  eslint-config-next: ^15
  prettier: ^3.6
  ts-node: ^10.9
  typescript: ^5
  vitest: ^3.2
  typescript-eslint: ^8.40
  '@auth/typeorm-adapter': ^2.10
  zod: ^4.1
  "@next/eslint-plugin-next": "^15.5"
  "next-auth": "5.0.0-beta.29"
  "lodash": "^4.17.21"
  "@types/lodash": "^4.17.20"

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'
  - canvas
  - core-js
  - esbuild
