services:
  pg-db:
    command: postgres -c work_mem=8000
    restart: always
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=emagrecer_db
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD-SHELL
        - pg_isready
      timeout: 5s
    image: postgres:17
    shm_size: 1gb
    ports:
      - '5432:5432'
